// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveWithGamepad.h"
#include "Subsystems/DriveTrain.h"
#include "OI.h"
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveWithGamepad::DriveWithGamepad(double LeftThumbStick_Y_Axis, double RightThumbStick_Y_Axis): frc::Command() {
    m_LeftThumbStick_Y_Axis = LeftThumbStick_Y_Axis;
    m_RightThumbStick_Y_Axis = RightThumbStick_Y_Axis;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    Requires(Robot::driveTrain.get());
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveWithGamepad::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveWithGamepad::Execute() {
	auto driverJoystick = Robot::oi->getGamepad();  // originaly auto&


	if ((bool) driverJoystick->GetRawButton(5))
	{
		Robot::driveTrain->drivePrecisionGamepad(-driverJoystick->GetRawAxis(1) ,-driverJoystick->GetRawAxis(5));
	}
	else
	{
		Robot::driveTrain->driveGamepad(-driverJoystick->GetRawAxis(1) ,-driverJoystick->GetRawAxis(5));
	}
}

// Make this return true when this Command no longer needs to run execute()
bool DriveWithGamepad::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveWithGamepad::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveWithGamepad::Interrupted() {

}
