// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LiftRun.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LiftRun::LiftRun(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LiftRun::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void LiftRun::Execute() {
	auto driverJoystick = Robot::oi->getGamepad();  // originaly auto&


	double liftSpeed = 0;
	liftSpeed = 0;

	double downSpeed = driverJoystick->GetRawAxis(2);
	double upSpeed = driverJoystick->GetRawAxis(3);

	if (upSpeed >= .50)
	{
		liftSpeed = upSpeed;
		if(downSpeed >= .50)
		{
			liftSpeed = 0;
		}

	}
	else
	{
		liftSpeed = -downSpeed;
	}

	Robot::lift->RunLift(liftSpeed);

}

// Make this return true when this Command no longer needs to run execute()
bool LiftRun::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void LiftRun::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftRun::Interrupted() {

}
