// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::Encoder> driveTrainEncoderRight;
	static std::shared_ptr<frc::Encoder> driveTrainEncoderLeft;
	static std::shared_ptr<WPI_TalonSRX> driveTrainDriveLeft;
	static std::shared_ptr<WPI_TalonSRX> driveTrainDriveRight;
	static std::shared_ptr<frc::DifferentialDrive> driveTrainTank;
	static std::shared_ptr<frc::AnalogGyro> driveTrainAnalogGyro1;
	static std::shared_ptr<WPI_TalonSRX> driveTrainFollowerLeft;
	static std::shared_ptr<WPI_TalonSRX> driveTrainFollowerRight;
	static std::shared_ptr<frc::SpeedController> liftLift;
	static std::shared_ptr<frc::DigitalInput> liftBottomSwitch;
	static std::shared_ptr<frc::DigitalInput> liftTopSwitch;
	static std::shared_ptr<frc::SpeedController> intakeIntakeLeft;
	static std::shared_ptr<frc::SpeedController> intakeIntakeRight;
	static std::shared_ptr<frc::SpeedController> riserRiser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
